# Generated by Django 4.0.4 on 2022-11-22 00:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0014_perfil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='cidade',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='cadastros.cidade', verbose_name='Cidade'),
        ),
    ]
