# Generated by Django 4.0.4 on 2022-11-23 03:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cadastros', '0015_alter_perfil_cidade'),
    ]

    operations = [
        migrations.CreateModel(
            name='Haras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120, verbose_name='Nome')),
                ('descricao', models.CharField(max_length=255, verbose_name='Descrição')),
                ('telefone_primario', models.CharField(max_length=16)),
                ('telefone_secundario', models.CharField(max_length=16, null=True)),
                ('status', models.CharField(max_length=20, verbose_name='Status')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('modificado_em', models.DateTimeField(auto_now=True)),
                ('cidade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.cidade', verbose_name='Cidade')),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='haras_criado_por', to=settings.AUTH_USER_MODEL)),
                ('modificado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='haras_atualizado_por', to=settings.AUTH_USER_MODEL)),
                ('proprietario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='haras_proprietario', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ImagemHaras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='imagensHaras')),
                ('haras', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastros.haras')),
            ],
        ),
        migrations.AddField(
            model_name='cavalo',
            name='haras',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cadastros.haras', verbose_name='Haras'),
        ),
    ]
