# Generated by Django 4.0.4 on 2022-11-23 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0016_haras_imagemharas_cavalo_haras'),
    ]

    operations = [
        migrations.AddField(
            model_name='haras',
            name='imagem',
            field=models.ImageField(default=1, upload_to='imagensHaras'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='ImagemHaras',
        ),
    ]
