# Generated by Django 4.0.4 on 2022-11-23 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0017_haras_imagem_delete_imagemharas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='haras',
            name='imagem',
        ),
        migrations.AddField(
            model_name='haras',
            name='logo',
            field=models.ImageField(default=1, upload_to='logoHaras'),
            preserve_default=False,
        ),
    ]
