# Generated by Django 4.1.3 on 2022-11-27 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0018_remove_haras_imagem_haras_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cavalo',
            name='descricao',
            field=models.CharField(max_length=1500, verbose_name='Descrição'),
        ),
    ]
